controller_list:
  - name: position
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []
  - name: effort
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []